// svelteSolution/src/App.svelte
<script lang="ts">
  let title = "Svelte (from variable)"

  const modify = () => {
    title = "modified"
  }

  let username = ""
</script>

<div>Hello { title }</div>
<button on:click={modify}>Modify</button>
<hr>
<input type="text" bind:value={username}>
<button on:click={() => username = ""}>reset</button>
<button on:click={() => console.log(username)}>log</button>

// vueSolution/src/App.vue
<script setup lang="ts">
import { ref } from 'vue';

//let title = "Vue (from variable)"
const title = ref("Vue (from variable)")

const modify = () => {
  title.value = "modified"
}

const username = ref("")

const log = () => {
  console.log(username.value)
}

const reset = () => {
  username.value = ""
}
</script>

<template>
  <div>Hello {{ title }}</div>
  <button @click="modify">Modify</button>
  <hr>
  <input placeholder="Username" type="text" v-model="username">
  <button @click="reset">reset</button>
  <button @click="log">log</button>
</template>
