// angularSolution/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'Angular (from variable)';
  username = ""

  isShown = false

  fruits = [
    { name: "alma", color: "piros" },
    { name: "korte", color: "barna" },
    { name: "narancs", color: "narancssarga" },
    { name: "cseresznye", color: "piros" },
  ]

  reset() {
    this.username = ""
  }

  log() {
    console.log(this.username)
  }


  modify() {
    this.title = "modified"
  }
}

<div>Hello {{ title }}</div>
<button (click)="modify()">Modify</button>
<hr>
<input type="text" [(ngModel)]="username">
<button (click)="reset()">reset</button>
<button (click)="log()">log</button>

<hr />

<p *ngFor="let fruit of fruits" >{{fruit.name}} ({{fruit.color}})</p>

<section>
  <button (click)="isShown = !isShown">Toggle</button>
  <div *ngIf="isShown">Haho</div>
  <div *ngIf="!isShown">Secret</div>
</section>

// svelteSolution/src/App.svelte
<script lang="ts">
  let title = "Svelte (from variable)"

  const modify = () => {
    title = "modified"
  }

  let username = ""

  const fruits = [
    { name: "alma", color: "piros" },
    { name: "korte", color: "barna" },
    { name: "narancs", color: "narancssarga" },
    { name: "cseresznye", color: "piros" },
  ]

  let isShown = false
</script>

<div>Hello { title }</div>
<button on:click={modify}>Modify</button>
<hr>
<input type="text" bind:value={username}>
<button on:click={() => username = ""}>reset</button>
<button on:click={() => console.log(username)}>log</button>

<hr />

{#each fruits as fruit}
  <p class="text-warning">{ fruit.name } ({fruit.color})</p>
{/each}

<section>
  <button on:click={() => isShown = !isShown}>Toggle</button>
  {#if isShown}
    <div>Haho</div>
  {:else}
    <div>secret</div>
  {/if}
</section>
